// <auto-generated />
using System;
using FashionFace.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FashionFace.Repositories.Context.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20251211143314_AddDefaultRoles")]
    partial class AddDefaultRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("BodyType");

                    b.Property<string>("EyeColorType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("EyeColorType");

                    b.Property<string>("EyeShapeType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("EyeShapeType");

                    b.Property<string>("FaceType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FaceType");

                    b.Property<string>("HairColorType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairColorType");

                    b.Property<string>("HairLengthType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairLengthType");

                    b.Property<string>("HairType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairType");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("Height");

                    b.Property<string>("JawType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("JawType");

                    b.Property<string>("NoseType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("NoseType");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileId");

                    b.Property<string>("SexType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("SexType");

                    b.Property<int>("ShoeSize")
                        .HasColumnType("integer")
                        .HasColumnName("ShoeSize");

                    b.Property<string>("SkinToneType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("SkinToneType");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("AppearanceTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Country", "Name")
                        .IsUnique();

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.FemaleTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("AppearanceTraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("AppearanceTraitsId");

                    b.Property<string>("BustSizeType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("BustSizeType");

                    b.HasKey("Id");

                    b.HasIndex("AppearanceTraitsId")
                        .IsUnique();

                    b.ToTable("FemaleTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Landmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Landmark", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MaleTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("AppearanceTraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("AppearanceTraitsId");

                    b.Property<string>("FacialHairLengthType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FacialHairLengthType");

                    b.HasKey("Id");

                    b.HasIndex("AppearanceTraitsId")
                        .IsUnique();

                    b.ToTable("MaleTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("OptimizedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("OptimizedFileId");

                    b.Property<Guid>("OriginalFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("OriginalFileId");

                    b.HasKey("Id");

                    b.HasIndex("OptimizedFileId")
                        .IsUnique();

                    b.HasIndex("OriginalFileId")
                        .IsUnique();

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("OriginalMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("OriginalMediaId");

                    b.Property<Guid>("PreviewMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("PreviewMediaId");

                    b.HasKey("Id");

                    b.HasIndex("OriginalMediaId")
                        .IsUnique();

                    b.HasIndex("PreviewMediaId")
                        .IsUnique();

                    b.ToTable("MediaAggregate", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaAggregateTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("MediaAggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("MediaAggregateId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("PositionIndex");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("MediaAggregateId");

                    b.HasIndex("TagId");

                    b.ToTable("MediaAggregateTag", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileId");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RelativePath");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("MediaFile", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("BuildingId");

                    b.Property<Guid>("LandmarkId")
                        .HasColumnType("uuid")
                        .HasColumnName("LandmarkId");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Street");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.HasIndex("LandmarkId")
                        .IsUnique();

                    b.ToTable("Place", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid")
                        .HasColumnName("TalentId");

                    b.HasKey("Id");

                    b.HasIndex("TalentId")
                        .IsUnique();

                    b.ToTable("Portfolio", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.PortfolioMediaAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("MediaAggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("MediaAggregateId");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("PortfolioId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("PositionIndex");

                    b.HasKey("Id");

                    b.HasIndex("MediaAggregateId")
                        .IsUnique();

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioMediaAggregate", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.PortfolioTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("PortfolioMediaAggregateId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("PositionIndex");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TagId");

                    b.ToTable("PortfolioTag", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AgeCategoryType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("AgeCategoryType");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.ProfileTalent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("PositionIndex");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileMediaId");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid")
                        .HasColumnName("TalentId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("TalentId")
                        .IsUnique();

                    b.ToTable("ProfileTalent", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Talent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("TalentType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("LocationType");

                    b.HasKey("Id");

                    b.ToTable("Talent", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.TalentLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("CityId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("LocationType");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("PlaceId");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid")
                        .HasColumnName("TalentId");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.HasIndex("TalentId");

                    b.ToTable("TalentLocation", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Profile", "Profile")
                        .WithOne("AppearanceTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.AppearanceTraits", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.FemaleTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.AppearanceTraits", "AppearanceTraits")
                        .WithOne("FemaleTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.FemaleTraits", "AppearanceTraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppearanceTraits");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MaleTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.AppearanceTraits", "AppearanceTraits")
                        .WithOne("MaleTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.MaleTraits", "AppearanceTraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppearanceTraits");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Media", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaFile", "OptimizedFile")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Media", "OptimizedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.MediaFile", "OriginalFile")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Media", "OriginalFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptimizedFile");

                    b.Navigation("OriginalFile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaAggregate", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Media", "OriginalMedia")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.MediaAggregate", "OriginalMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Media", "PreviewMedia")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.MediaAggregate", "PreviewMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalMedia");

                    b.Navigation("PreviewMedia");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaAggregateTag", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaAggregate", "MediaAggregate")
                        .WithMany("PortfolioMediaTagCollection")
                        .HasForeignKey("MediaAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Tag", "Tag")
                        .WithMany("PortfolioMediaTagCollection")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAggregate");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaFile", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Profile", "Profile")
                        .WithMany("MediaFileCollection")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Place", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Building", "Building")
                        .WithOne("Place")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Place", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Landmark", "Landmark")
                        .WithOne("Place")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Place", "LandmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Landmark");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolio", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Talent", "Talent")
                        .WithOne("Portfolio")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Portfolio", "TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.PortfolioMediaAggregate", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaAggregate", "MediaAggregate")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.PortfolioMediaAggregate", "MediaAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Portfolio", "Portfolio")
                        .WithMany("PortfolioMediaCollection")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAggregate");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.PortfolioTag", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Portfolio", "Portfolio")
                        .WithMany("PortfolioTagCollection")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Tag", "Tag")
                        .WithMany("PortfolioTagCollection")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profile", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", "ApplicationUser")
                        .WithOne("Profile")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Profile", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.ProfileTalent", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Profile", "Profile")
                        .WithMany("ProfileTalentCollection")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Talent", "Talent")
                        .WithOne("ProfileTalent")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.ProfileTalent", "TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.TalentLocation", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.City", "City")
                        .WithMany("TalentLocationCollection")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Place", "Place")
                        .WithOne("TalentLocation")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.TalentLocation", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Talent", "Talent")
                        .WithMany("TalentLocationCollection")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Place");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraits", b =>
                {
                    b.Navigation("FemaleTraits");

                    b.Navigation("MaleTraits");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Building", b =>
                {
                    b.Navigation("Place");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.City", b =>
                {
                    b.Navigation("TalentLocationCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Landmark", b =>
                {
                    b.Navigation("Place");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaAggregate", b =>
                {
                    b.Navigation("PortfolioMediaTagCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Place", b =>
                {
                    b.Navigation("TalentLocation");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolio", b =>
                {
                    b.Navigation("PortfolioMediaCollection");

                    b.Navigation("PortfolioTagCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profile", b =>
                {
                    b.Navigation("AppearanceTraits");

                    b.Navigation("MediaFileCollection");

                    b.Navigation("ProfileTalentCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Tag", b =>
                {
                    b.Navigation("PortfolioMediaTagCollection");

                    b.Navigation("PortfolioTagCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Talent", b =>
                {
                    b.Navigation("Portfolio");

                    b.Navigation("ProfileTalent");

                    b.Navigation("TalentLocationCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
