// <auto-generated />
using System;
using FashionFace.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FashionFace.Repositories.Context.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    partial class ApplicationDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.AppearanceTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("BodyType");

                    b.Property<string>("EyeColorType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("EyeColorType");

                    b.Property<string>("EyeShapeType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("EyeShapeType");

                    b.Property<string>("FaceType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FaceType");

                    b.Property<string>("HairColorType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairColorType");

                    b.Property<string>("HairLengthType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairLengthType");

                    b.Property<string>("HairType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairType");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("Height");

                    b.Property<string>("JawType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("JawType");

                    b.Property<string>("NoseType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("NoseType");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileId");

                    b.Property<string>("SexType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("SexType");

                    b.Property<int>("ShoeSize")
                        .HasColumnType("integer")
                        .HasColumnName("ShoeSize");

                    b.Property<string>("SkinToneType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("SkinToneType");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("AppearanceTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.FemaleTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppearanceTraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("AppearanceTraitsId");

                    b.Property<string>("BustSizeType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("BustSizeType");

                    b.HasKey("Id");

                    b.HasIndex("AppearanceTraitsId")
                        .IsUnique();

                    b.ToTable("FemaleTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.MaleTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppearanceTraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("AppearanceTraitsId");

                    b.Property<string>("FacialHairLengthType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FacialHairLengthType");

                    b.HasKey("Id");

                    b.HasIndex("AppearanceTraitsId")
                        .IsUnique();

                    b.ToTable("MaleTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.DossierEntities.Dossier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Dossier", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.DossierEntities.DossierMediaAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("DossierId");

                    b.Property<Guid>("MediaAggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("MediaAggregateId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.HasIndex("MediaAggregateId")
                        .IsUnique();

                    b.ToTable("DossierMediaAggregate", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.AppearanceTraitsDimensionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DimensionValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("DimensionValueId");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("DimensionValueId", "ProfileId")
                        .IsUnique();

                    b.ToTable("AppearanceTraitsDimensionValue", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.Dimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Code");

                    b.HasKey("Id");

                    b.ToTable("Dimension", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.DimensionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Code");

                    b.Property<Guid>("DimensionId")
                        .HasColumnType("uuid")
                        .HasColumnName("DimensionId");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId", "Code")
                        .IsUnique();

                    b.ToTable("DimensionValue", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.Filter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicationUserId");

                    b.Property<Guid>("FilterCriteriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Name");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("FilterCriteriaId")
                        .IsUnique();

                    b.ToTable("Filter", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TalentType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("TalentType");

                    b.HasKey("Id");

                    b.ToTable("FilterCriteria", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("BodyType");

                    b.Property<string>("EyeColorType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("EyeColorType");

                    b.Property<string>("EyeShapeType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("EyeShapeType");

                    b.Property<string>("FaceType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FaceType");

                    b.Property<Guid>("FilterCriteriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaId");

                    b.Property<string>("HairColorType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairColorType");

                    b.Property<string>("HairLengthType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairLengthType");

                    b.Property<string>("HairType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("HairType");

                    b.Property<string>("JawType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("JawType");

                    b.Property<string>("NoseType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("NoseType");

                    b.Property<string>("SexType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("SexType");

                    b.Property<string>("SkinToneType")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("SkinToneType");

                    b.HasKey("Id");

                    b.HasIndex("FilterCriteriaId")
                        .IsUnique();

                    b.ToTable("FilterCriteriaAppearanceTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaDimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DimensionValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("DimensionValueId");

                    b.Property<Guid>("FilterCriteriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaId");

                    b.HasKey("Id");

                    b.HasIndex("DimensionValueId");

                    b.HasIndex("FilterCriteriaId");

                    b.ToTable("FilterCriteriaDimension", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaFemaleTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BustSizeType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("BustSizeType");

                    b.Property<Guid>("FilterCriteriaAppearanceTraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaAppearanceTraitsId");

                    b.HasKey("Id");

                    b.HasIndex("FilterCriteriaAppearanceTraitsId")
                        .IsUnique();

                    b.ToTable("FilterCriteriaFemaleTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaHeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FilterCriteriaAppearanceTraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaAppearanceTraitsId");

                    b.Property<Guid?>("FilterCriteriaAppearanceTraitsId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FilterRangeValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterRangeValueId");

                    b.HasKey("Id");

                    b.HasIndex("FilterCriteriaAppearanceTraitsId")
                        .IsUnique();

                    b.HasIndex("FilterCriteriaAppearanceTraitsId1")
                        .IsUnique();

                    b.HasIndex("FilterRangeValueId")
                        .IsUnique();

                    b.ToTable("FilterCriteriaHeight", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("CityId");

                    b.Property<Guid>("FilterCriteriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaId");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("LocationType");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("PlaceId");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("FilterCriteriaId")
                        .IsUnique();

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.ToTable("FilterCriteriaLocation", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaMaleTraits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FacialHairLengthType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("FacialHairLengthType");

                    b.Property<Guid>("FilterCriteriaAppearanceTraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaAppearanceTraitsId");

                    b.HasKey("Id");

                    b.HasIndex("FilterCriteriaAppearanceTraitsId")
                        .IsUnique();

                    b.ToTable("FilterCriteriaMaleTraits", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaShoeSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FilterCriteriaAppearanceTraitsId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaAppearanceTraitsId");

                    b.Property<Guid>("FilterRangeValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterRangeValueId");

                    b.HasKey("Id");

                    b.HasIndex("FilterCriteriaAppearanceTraitsId")
                        .IsUnique();

                    b.HasIndex("FilterRangeValueId")
                        .IsUnique();

                    b.ToTable("FilterCriteriaShoeSize", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FilterCriteriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("FilterCriteriaId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("FilterCriteriaId");

                    b.HasIndex("TagId");

                    b.ToTable("FilterCriteriaTag", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterRangeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Max")
                        .HasColumnType("integer")
                        .HasColumnName("Max");

                    b.Property<int>("Min")
                        .HasColumnType("integer")
                        .HasColumnName("Min");

                    b.HasKey("Id");

                    b.ToTable("FilterRangeValue", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Country", "Name")
                        .IsUnique();

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Landmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Landmark", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("CityId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("LocationType");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("PlaceId");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid")
                        .HasColumnName("TalentId");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PlaceId")
                        .IsUnique();

                    b.HasIndex("TalentId");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("BuildingId");

                    b.Property<Guid>("LandmarkId")
                        .HasColumnType("uuid")
                        .HasColumnName("LandmarkId");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Street");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.HasIndex("LandmarkId")
                        .IsUnique();

                    b.ToTable("Place", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaEntities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OptimizedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("OptimizedFileId");

                    b.Property<Guid>("OriginalFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("OriginalFileId");

                    b.HasKey("Id");

                    b.HasIndex("OptimizedFileId")
                        .IsUnique();

                    b.HasIndex("OriginalFileId")
                        .IsUnique();

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OriginalMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("OriginalMediaId");

                    b.Property<Guid>("PreviewMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("PreviewMediaId");

                    b.HasKey("Id");

                    b.HasIndex("OriginalMediaId")
                        .IsUnique();

                    b.HasIndex("PreviewMediaId")
                        .IsUnique();

                    b.ToTable("MediaAggregate", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregateTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaAggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("MediaAggregateId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("MediaAggregateId");

                    b.HasIndex("TagId");

                    b.ToTable("MediaAggregateTag", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaEntities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileId");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RelativePath");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("MediaFile", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolios.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid")
                        .HasColumnName("TalentId");

                    b.HasKey("Id");

                    b.HasIndex("TalentId")
                        .IsUnique();

                    b.ToTable("Portfolio", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolios.PortfolioMediaAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaAggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("MediaAggregateId");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("PortfolioId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MediaAggregateId")
                        .IsUnique();

                    b.HasIndex("PortfolioId");

                    b.ToTable("PortfolioMediaAggregate", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolios.PortfolioTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("PortfolioMediaAggregateId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("TagId");

                    b.ToTable("PortfolioTag", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgeCategoryType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("AgeCategoryType");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profiles.ProfileMediaAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaAggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("MediaAggregateId");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("MediaAggregateId")
                        .IsUnique();

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ProfileMediaAggregate", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profiles.ProfileTalent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("ProfileMediaId");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid")
                        .HasColumnName("TalentId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("TalentId")
                        .IsUnique();

                    b.ToTable("ProfileTalent", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Talents.Talent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TalentType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("LocationType");

                    b.HasKey("Id");

                    b.ToTable("Talent", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Talents.TalentMediaAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaAggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("MediaAggregateId");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid")
                        .HasColumnName("TalentId");

                    b.HasKey("Id");

                    b.HasIndex("MediaAggregateId")
                        .IsUnique();

                    b.HasIndex("TalentId")
                        .IsUnique();

                    b.ToTable("TalentMediaAggregate", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SettingsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SettingsId");

                    b.ToTable("UserToUserChat", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicationUserId");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("ChatId");

                    b.Property<double>("LastReadMessagePositionIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("LastReadMessagePositionIndex");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Type");

                    b.Property<Guid?>("UserToUserChatId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserToUserChatId");

                    b.ToTable("UserToUserChatApplicationUser", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("InitiatorUserId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Status");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("TargetUserId");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("UserToUserChatInvitation", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("ChatId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("MessageId");

                    b.Property<double>("PositionIndex")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("UserToUserChatId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserToUserChatId");

                    b.ToTable("UserToUserChatMessage", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid")
                        .HasColumnName("ChatId");

                    b.Property<string>("ChatType")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("ChatType");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("UserToUserChatSettings", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicationUserId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserToUserMessage", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.AppearanceTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Profiles.Profile", "Profile")
                        .WithOne("AppearanceTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.AppearanceTraits", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.FemaleTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.AppearanceTraits", "AppearanceTraits")
                        .WithOne("FemaleTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.FemaleTraits", "AppearanceTraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppearanceTraits");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.MaleTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.AppearanceTraits", "AppearanceTraits")
                        .WithOne("MaleTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.MaleTraits", "AppearanceTraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppearanceTraits");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.DossierEntities.Dossier", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Profiles.Profile", "Profile")
                        .WithOne("Dossier")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.DossierEntities.Dossier", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.DossierEntities.DossierMediaAggregate", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.DossierEntities.Dossier", "Dossier")
                        .WithMany("DossierMediaCollection")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", "MediaAggregate")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.DossierEntities.DossierMediaAggregate", "MediaAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");

                    b.Navigation("MediaAggregate");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.AppearanceTraitsDimensionValue", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.DimensionValue", "DimensionValue")
                        .WithMany()
                        .HasForeignKey("DimensionValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Profiles.Profile", "Profile")
                        .WithMany("AppearanceTraitsDimensionValueCollection")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimensionValue");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.DimensionValue", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.Dimension", "Dimension")
                        .WithMany("DimensionValueCollection")
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimension");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.Filter", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteria", "FilterCriteria")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.Filter", "FilterCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("FilterCriteria");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteria", "FilterCriteria")
                        .WithOne("AppearanceTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", "FilterCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterCriteria");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaDimension", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.DimensionValue", "DimensionValue")
                        .WithMany()
                        .HasForeignKey("DimensionValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteria", "FilterCriteria")
                        .WithMany("DimensionCollection")
                        .HasForeignKey("FilterCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimensionValue");

                    b.Navigation("FilterCriteria");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaFemaleTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", "FilterCriteriaAppearanceTraits")
                        .WithOne("FemaleTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaFemaleTraits", "FilterCriteriaAppearanceTraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterCriteriaAppearanceTraits");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaHeight", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", "FilterCriteriaAppearanceTraits")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaHeight", "FilterCriteriaAppearanceTraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", null)
                        .WithOne("Height")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaHeight", "FilterCriteriaAppearanceTraitsId1")
                        .HasConstraintName("FK_FilterCriteriaHeight_FilterCriteriaAppearanceTraits_Filter~1");

                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterRangeValue", "FilterRangeValue")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaHeight", "FilterRangeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterCriteriaAppearanceTraits");

                    b.Navigation("FilterRangeValue");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaLocation", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Locations.City", "City")
                        .WithMany("FilterLocationCollection")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteria", "FilterCriteria")
                        .WithOne("Location")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaLocation", "FilterCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Locations.Place", "Place")
                        .WithOne("FilterLocation")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaLocation", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("FilterCriteria");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaMaleTraits", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", "FilterCriteriaAppearanceTraits")
                        .WithOne("MaleTraits")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaMaleTraits", "FilterCriteriaAppearanceTraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterCriteriaAppearanceTraits");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaShoeSize", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", "FilterCriteriaAppearanceTraits")
                        .WithOne("ShoeSize")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaShoeSize", "FilterCriteriaAppearanceTraitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterRangeValue", "FilterRangeValue")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaShoeSize", "FilterRangeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterCriteriaAppearanceTraits");

                    b.Navigation("FilterRangeValue");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaTag", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Filters.FilterCriteria", "FilterCriteria")
                        .WithMany("TagCollection")
                        .HasForeignKey("FilterCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Tags.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterCriteria");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Location", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Locations.City", "City")
                        .WithMany("LocationCollection")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Locations.Place", "Place")
                        .WithOne("Location")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Locations.Location", "PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Talents.Talent", "Talent")
                        .WithMany("LocationCollection")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Place");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Place", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Locations.Building", "Building")
                        .WithOne("Place")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Locations.Place", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Locations.Landmark", "Landmark")
                        .WithOne("Place")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Locations.Place", "LandmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Landmark");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaEntities.Media", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.MediaFile", "OptimizedFile")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.MediaEntities.Media", "OptimizedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.MediaFile", "OriginalFile")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.MediaEntities.Media", "OriginalFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptimizedFile");

                    b.Navigation("OriginalFile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.Media", "OriginalMedia")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", "OriginalMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.Media", "PreviewMedia")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", "PreviewMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalMedia");

                    b.Navigation("PreviewMedia");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregateTag", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", "MediaAggregate")
                        .WithMany()
                        .HasForeignKey("MediaAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Tags.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAggregate");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.MediaEntities.MediaFile", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Profiles.Profile", "Profile")
                        .WithMany("MediaFileCollection")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolios.Portfolio", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Talents.Talent", "Talent")
                        .WithOne("Portfolio")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Portfolios.Portfolio", "TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolios.PortfolioMediaAggregate", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", "MediaAggregate")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Portfolios.PortfolioMediaAggregate", "MediaAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Portfolios.Portfolio", "Portfolio")
                        .WithMany("PortfolioMediaCollection")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAggregate");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolios.PortfolioTag", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Portfolios.Portfolio", "Portfolio")
                        .WithMany("PortfolioTagCollection")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Tags.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profiles.Profile", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Profiles.Profile", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profiles.ProfileMediaAggregate", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", "MediaAggregate")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Profiles.ProfileMediaAggregate", "MediaAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Profiles.Profile", "Profile")
                        .WithOne("ProfileMediaAggregate")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Profiles.ProfileMediaAggregate", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAggregate");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profiles.ProfileTalent", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.Profiles.Profile", "Profile")
                        .WithMany("ProfileTalentCollection")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Talents.Talent", "Talent")
                        .WithOne("ProfileTalent")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Profiles.ProfileTalent", "TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Talents.TalentMediaAggregate", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.MediaEntities.MediaAggregate", "MediaAggregate")
                        .WithOne()
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Talents.TalentMediaAggregate", "MediaAggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.Talents.Talent", "Talent")
                        .WithOne("TalentMediaAggregate")
                        .HasForeignKey("FashionFace.Repositories.Context.Models.Talents.TalentMediaAggregate", "TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAggregate");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChat", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatApplicationUser", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChat", null)
                        .WithMany("UserCollection")
                        .HasForeignKey("UserToUserChatId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatInvitation", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", "InitiatorUser")
                        .WithMany()
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InitiatorUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatMessage", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChat", null)
                        .WithMany("MessageCollection")
                        .HasForeignKey("UserToUserChatId");

                    b.Navigation("Chat");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChatSettings", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserMessage", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FashionFace.Repositories.Context.Models.IdentityEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.AppearanceTraitsEntities.AppearanceTraits", b =>
                {
                    b.Navigation("FemaleTraits");

                    b.Navigation("MaleTraits");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.DossierEntities.Dossier", b =>
                {
                    b.Navigation("DossierMediaCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.Dimension", b =>
                {
                    b.Navigation("DimensionValueCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteria", b =>
                {
                    b.Navigation("AppearanceTraits");

                    b.Navigation("DimensionCollection");

                    b.Navigation("Location");

                    b.Navigation("TagCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Filters.FilterCriteriaAppearanceTraits", b =>
                {
                    b.Navigation("FemaleTraits");

                    b.Navigation("Height");

                    b.Navigation("MaleTraits");

                    b.Navigation("ShoeSize");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Building", b =>
                {
                    b.Navigation("Place");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.City", b =>
                {
                    b.Navigation("FilterLocationCollection");

                    b.Navigation("LocationCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Landmark", b =>
                {
                    b.Navigation("Place");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Locations.Place", b =>
                {
                    b.Navigation("FilterLocation");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Portfolios.Portfolio", b =>
                {
                    b.Navigation("PortfolioMediaCollection");

                    b.Navigation("PortfolioTagCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Profiles.Profile", b =>
                {
                    b.Navigation("AppearanceTraits");

                    b.Navigation("AppearanceTraitsDimensionValueCollection");

                    b.Navigation("Dossier");

                    b.Navigation("MediaFileCollection");

                    b.Navigation("ProfileMediaAggregate");

                    b.Navigation("ProfileTalentCollection");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.Talents.Talent", b =>
                {
                    b.Navigation("LocationCollection");

                    b.Navigation("Portfolio");

                    b.Navigation("ProfileTalent");

                    b.Navigation("TalentMediaAggregate");
                });

            modelBuilder.Entity("FashionFace.Repositories.Context.Models.UserToUserChats.UserToUserChat", b =>
                {
                    b.Navigation("MessageCollection");

                    b.Navigation("UserCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
