insert into public."AspNetUsers" (
    "Id",
    "PhoneNumberConfirmed",
    "TwoFactorEnabled",
    "LockoutEnabled",
    "UserName",
    "NormalizedUserName",
    "Email",
    "NormalizedEmail",
    "EmailConfirmed",
    "PasswordHash",
    "SecurityStamp",
    "ConcurrencyStamp",
    "AccessFailedCount"
)
values (
           gen_random_uuid(),
           'false',
           'false',
           'false',
           'admin',
           'ADMIN',
           'admin@ff.ai',
           'ADMIN@FF.AI',
           'true',
           'AQAAAAIAAYagAAAAEHkoECCwkPGF2Vo+LK5oK8M5T+eXEvq9AZSjcatpvaetuCz201hL1HoStlA0g6oovQ==',
           'U647ST5RBQF2T2AEZ7JBOOEXW5PCMYBP',
           gen_random_uuid(),
           0
       );